### ISSUE TITLE
Dashboard: Minutes are missing from the task duration when duration is over 1 hour

### ISSUE THREAD

**Issue by doze** [M-Files/VAF.Extensions.Community#56] opened 2022-03-22 11:06 UTC
When task duration goes over 1 hour the "Duration" column in the Dashboard user interface does not show minutes. The value shows like "1 Hours, , 21 seconds".

**Comment by CraigHawker** [comment] 2022-03-22 11:08
Hi @doze,

Can you confirm the version that you tested with?  I ask as there have been some changes to the dashboard rendering in the latest preview, and want to confirm whether the bug still exists there.

Thank you.

Craig.

**Comment by doze** [comment] 2022-03-22 11:11
1.3.0.14 is the vaf.extensions version

**Comment by CraigHawker** [comment] 2022-03-22 12:06
I believe that this is a duplicate of issue #40, which was fixed in commit 0134ead012f1c807c3d01997fc91845213972d93.  My concern is that this should have been part of the 1.3.0.14 release, so I'm not sure why you're still seeing it in that release.

**Comment by CraigHawker** [comment] 2022-06-20 07:32
Closed as believed-fixed in new releases (we added a number of unit tests around this a few months ago, and fixed some rendering issues).
If this persists then please re-open with a screenshot and details of versions.

**Closed by CraigHawker** 2022-06-20 07:32 UTC
Labels: bug
